### ISSUE TITLE
Cannot read property 'lightest' of undefined  

### ISSUE THREAD

**Issue by ludan1107743896** [lumpyin/vikingship#1]
## 您后期引入stroybook 之后有以下问题吗？
```
Cannot read property 'lightest' of undefined

TypeError: Cannot read property 'lightest' of undefined
    at getScrollAreaStyles (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:21928:78)
    at http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:12656:100
    at updateContextConsumer (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:162572:19)
    at beginWork (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:162929:14)
    at HTMLUnknownElement.callCallback (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:144456:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:144505:16)
    at invokeGuardedCallback (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:144560:31)
    at beginWork$1 (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:167471:7)
    at performUnitOfWork (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:166425:12)
    at workLoopSync (http://localhost:9009/vendors~main.282a4ef1766b9efc3ad2.bundle.js:166398:22)
```

**Comment by ludan1107743896** [comment]
已经做修改，版本问题，webpack 版本过高，降下版本，问题得到了解决。
